### ISSUE TITLE
Tests failing is not blocking

### ISSUE THREAD

**Issue by igoumiri** [LLNL/MuyGPyS#132]
This typo https://github.com/LLNL/MuyGPyS/blob/a849e40177aaf30e4bfd7c6dbaded8f3db8ff887/.github/workflows/develop-test.yml#L42

makes me think that the tests can fail undetected. They might need to be chained with `&&`.

**Comment by igoumiri** [comment]
Relatedly, I ran this https://github.com/LLNL/MuyGPyS/blob/a849e40177aaf30e4bfd7c6dbaded8f3db8ff887/.github/workflows/develop-test.yml#L33-L34

manually and it found a lot of issues. Is `--exit-zero` actually making it pass when it shouldn't?

**Comment by igoumiri** [comment]
I think so but you would only see the warnings if you looked for them.

**Comment by bwpriest** [comment]
> This typo

You're right, that is a mistake. I'll change it.

> They might need to be chained with `&&`.

I don't think that is necessary.

**Comment by bwpriest** [comment]
PR #133 fixes the bug and updates the formatting throughout to match PEP requirements (where possible), and updates the `flake8` linting call so that it now finds no issues. There are 2 items blocking me from merging this in:
1. Current PRs should get merged first, as I had to change most of the files in the repo and it will be easier for me to merge those changes myself than to go the other way
2. We should decide whether we actually want to turn off `--exit-zero`, since if we do small formatting foibles (e.g. unused imports) will cause the CI to crash until they are fixed. I am not opposed _prima facie_, but this change will certainly result in more failed CI checks for developers due to small issues. @alecmdunton and @igoumiri, please let me know what behavior you prefer.

**Comment by igoumiri** [comment]
I'm fine either way but I don't mind more failed CI checks. I rarely get things right on the first try anyway. 🙂 

Also, I opened the issue because I thought failing tests were undetected. If that's not the case, we can close it.

**Comment by bwpriest** [comment]
Ok sounds good. Everyone might want to start practicing running flake8 before pushing to PRs. I'll wait to merge into develop until after the anisotropic PR gets merged.

**Comment by bwpriest** [comment]
I addressed this with PR #133. It is prudent to run `sh scripts/flake/fatal.sh` and `sh scripts/flake/issues.sh` before pushing commits from now on.
