### ISSUE TITLE
Anisotropic Modeling 

### ISSUE THREAD

**Issue by alecmdunton** [LLNL/MuyGPyS#88]
We need to add a feature that allows for anisotropic modeling. This will involve changing the optimization chassis and creating functionality that takes individual distance tensors, weights them, and produces the distance tensor for the full dataset.

**Comment by bwpriest** [comment]
PR #107 created a package, `MuyGPyS.gp.distortion` that holds the `IsotropicDistortion` logic. We will need to create an `AnisotropicDistortion` class therein, although it will be more involved because it has parameters (which can be optimization targets). This class will need `get_opt_fn` and `get_optim_params` methods that will have to hook into those of `RBF`/`Matern`. `IsotropicDistortion` will need its own version of those functions, although they will effectively be no-ops because there are no parameters.

**Comment by bwpriest** [comment]
We'll need to think about how to encourage users to not learn a separate length scale in a stationary kernel when we're using anisotropy. Should we pull the length scale fully into the distortion model? If so, I don't know if it makes sense to use `TensorHyperparameter`.

**Comment by bwpriest** [comment]
> Do we want `BenchmarkGP` to support anisotropic modeling? Looking at it now it should actually be really straightforward.

Ultimately yes, but I think we'll need to rewrite how the `BenchmarkGP` creates distance tensors. We can leave that for a later push unless you have momentum and want to do it now.

**Comment by bwpriest** [comment]
We should not make software decisions to accommodate `BenchmarkGP`, because it is not a user-facing class. It is fine to do suboptimal stuff therein, although I would prefer that we modify it to use `IsotropicDistortion` and `AnisotropicDistortion` in the same way that `MuyGPS` does to make it more maintainable. Again, we can leave that for later if you want to.

**Comment by bwpriest** [comment]
I'd ignore `tests/predict.py`. We'll probably drop that one or refactor it in the relatively near future. It will be hard/impossible to add anything meaningful to `tests/optimize.py` if the loss functions are not sensitive to length scales. We've only ever tested the recovery of `sigma_sq` and `nu` therein, and it is kinda broken right now anyway. We definitely need tests in `tests/backend` though. We probably want to copy all the tests that use isotropic kernels using anisotropic kernels, although that will be a lot of keystrokes. It might be worth figuring out if there is a way to automate those tests - i.e. give a `DistortionModel` and a `NoiseModel` to a function that then creates and runs all of the relevant tests. That will likely be a little nontrivial, and would probably be best left to a subsequent PR.

**Comment by bwpriest** [comment]
Addressed with PR #127
